
modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.


license="All rights reserved"

[[mods]] #mandatory
modId="baked_bread" #mandatory
version="1.6.3" #mandatory
displayName="Baked Bread" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/addition-breads" #optional
logoFile="mod_icon.png" #optional
credits="Thanks for Forge to give me the way to this mod. Also Thanks to: TechnoVision" #optional
authors="Khanhpham05" #optional
description='''
Just a bread but it cooked and yummy
'''
[[dependencies.baked_bread]] #optional
 
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
